import os
Import('env', 'progressbar', 'target_bin_dir')

#lattice = env.Library('lattice', ['lattice.cpp', 'cluster_counter.cpp', 'noise_lattice.cpp', 'lattice_integrator.cpp', 'lattice_models.cpp', 'fftw3_wrapper.cpp'])

lattice_plugin_registration = env.Library('lattice_plugin_registration', ['lattice_plugin_registration.cpp'])

lattice = env.Library('lattice', ['rds_helper.cpp', 'cluster_counter.cpp', 'noise_generator.cpp', 'noise_lattice.cpp', 'fftw3_wrapper.cpp'])