######################################################################
# Automatically generated by qmake (1.07a) Wed Nov 28 15:55:32 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h plotwindow.h
SOURCES += main.cpp mainwindow.cpp plotwindow.cpp
TRANSLATIONS += hellotr_la.ts
